application: lyontrack
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /
  static_dir: LyonTracks


- url: /.*
  script: main.app
  secure: always


libraries:
- name: jinja2
  version: latest

# image files
#- url: /Images/(.*\.(bmp|gif|ico|jpeg|jpg|png))
#  static_files: static/\1
#  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^.*\.pyc$
